baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Robin Lovelace's website. Energy. Transport. Technology. Change the World."
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Publications"
    url = "/publications/"
[[menu.main]]
    name = "Presentations"
    url = "/presentations/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/robinlovelace"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/robinlovelace"

[params]
    description = "Robin Lovelace's website. Energy. Transport. Technology. Change the World."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

publishDir = "robinlovelace.github.io"